services:
  unshackledkitchen:
    container_name: unshackled-kitchen
    image: unshackled-kitchen
    build:
      context: ../../..
      dockerfile: ./src/Kitchen/Unshackled.Fitness.My/Dockerfile
    env_file: 
      - path: ./appsettings.env
        required: true
    restart: unless-stopped
    volumes:
      - //r/Containers/UnshackledKitchen/content/households:/app/wwwroot/content/households
      - //r/Containers/UnshackledKitchen/data:/app/Data
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    ports: 
      - 5590:8081
    